sudo: false
language: node_js
node_js:
  - "8"
  - "10"
# temp workaround for travis not having a recent version of yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - npm test
