name: Publish with Lerna

on:
  push:
    branches:
    - master

permissions:
  id-token: write
  contents: write

jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
    - name: yarn config
      run: yarn config set ignore-engines true
    - name: Git Identity
      run: |
        git config --global user.name 'Loic Mahieu'
        git config --global user.email 'mahieuloic@gmail.com'
        git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    - name: Pulling
      run: git pull
    - name: Install dependencies
      run: yarn install --pure-lockfile
    - name: Build
      run: yarn build
    - name: Publish with Lerna
      run: yarn lerna publish --yes --message 'chore(release)'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
